# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  submodules: recursive

- powershell: |
    mkdir build
    $ProgressPreference = 'SilentlyContinue'
    wget "https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win64/nasm-2.14.02-win64.zip" -O "nasm.zip"
  displayName: 'Download NASM'

- task: ExtractFiles@1
  inputs:
    destinationFolder: 'build'

- script: |
    cd submodules\openssl
    SET PATH=%PATH%;%BUILD_SOURCESDIRECTORY%\build\nasm-2.14.02
    pwd
    perl Configure --debug VC-WIN32 no-shared
    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\VsDevCmd.bat
    nmake
  displayName: 'Run a one-line script'