# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- template: ./templates/job-build.yml
  parameters:
    command: VC-WIN64A --debug
    vcvars: -arch=amd64
    name: Windows_Debug_x64

- template: ./templates/job-build.yml
  parameters:
    command: VC-WIN64A
    vcvars: -arch=amd64
    name: Windows_Release_x64

- template: ./templates/job-build.yml
  parameters:
    command: VC-WIN64A-UWP --debug
    vcvars: -arch=amd64 -app_platform=UWP
    name: UWP_Debug_x64

- template: ./templates/job-build.yml
  parameters:
    command: VC-WIN64A-UWP
    vcvars: -arch=amd64 -app_platform=UWP
    name: UWP_Release_x64

- template: ./templates/job-build.yml
  parameters:
    command: VC-WIN32 --debug
    name: Windows_Debug_x32

- template: ./templates/job-build.yml
  parameters:
    command: VC-WIN32
    name: Windows_Release_x32

- template: ./templates/job-build.yml
  parameters:
    command: VC-WIN32-UWP --debug
    vcvars: -app_platform=UWP
    name: UWP_Debug_x32

- template: ./templates/job-build.yml
  parameters:
    command: VC-WIN32-UWP
    vcvars: -app_platform=UWP
    name: UWP_Release_x32
