# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  submodules: recursive

- script: |
    cd submodules\openssl
    pwd
    perl Configure --debug VC-WIN32 no-shared
  displayName: 'Run a one-line script'