parameters:
  command: ''
  vcvars: ''
  name: ''


jobs:
- job: build_${{ parameters.name }}

  pool:
    vmImage: 'windows-2019'
  
  steps:
  - checkout: self
    submodules: recursive

  - powershell: |
      mkdir build
      $ProgressPreference = 'SilentlyContinue'
      wget "https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win64/nasm-2.14.02-win64.zip" -O "nasm.zip"
    displayName: 'Download NASM'

  - task: ExtractFiles@1
    inputs:
      destinationFolder: 'build'

  - script: |
      cd submodules\openssl
      SET PATH=%PATH%;%BUILD_SOURCESDIRECTORY%\build\nasm-2.14.02

      echo ${{ parameters.command }}

      perl Configure ${{ parameters.command }} no-shared
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" ${{ parameters.vcvars }}
      nmake
      dir
    displayName: 'Build'

  - task: CopyFiles@2
    displayName: Move Build Artifacts
    inputs:
      sourceFolder: submodules\openssl
      contents: |
        *.lib
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    displayName: Upload Build Artifacts
    inputs:
      artifactName: drop
      pathToPublish: $(Build.ArtifactStagingDirectory)
      parallel: true